AMB2275_TANUJA SL

In [ ]:
import pandas as pd
production=pd.Series([30,60,45,25],
                     index=["wheat","rice","maize","barley"]
)
print(production)

wheat     30
rice      60
maize     45
barley    25
dtype: int64

In [ ]:
#by crop name label
print(production['rice'])
print(production.loc["rice"])

60
60

In [ ]:
#by position
print(production[1])
print(production.iloc[1])

60
60

/tmp/ipython-input-408681856.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(production[1])

In [ ]:
print(production.sum())
print(production.mean())
print(production.max())
print(production.min())

160
40.0
60
25

In [ ]:
#increase all crop production by 10%(good harvest year)
increased_production=production*1.1
print(increased_production)

wheat     33.0
rice      66.0
maize     49.5
barley    27.5
dtype: float64

In [ ]:
#crops with production greater than 40tons
high_production=production[production>40]
print(high_production)
print()

print(production>40)

rice     60
maize    45
dtype: int64

wheat     False
rice       True
maize      True
barley    False
dtype: bool

In [ ]:
import pandas as pd
df =pd.DataFrame({
    "crop": ["wheat","rice","maize","barley"],
    "yield":[30,60,45,25],
    "region":["east","west","north","south"]
},index=["a","b","c","d"])
print(df)
print()
print(df.loc["b"])
print(df.loc["b", ["crop", "region"]])

     crop  yield region
a   wheat     30   east
b    rice     60   west
c   maize     45  north
d  barley     25  south

crop      rice
yield       60
region    west
Name: b, dtype: object
crop      rice
region    west
Name: b, dtype: object

In [ ]:
print(df.loc[df["yield"]>40,["crop","yield"]])#conditional statement

    crop  yield
b   rice     60
c  maize     45

In [ ]:
print(df.iloc[[0,2]])

    crop  yield region
a  wheat     30   east
c  maize     45  north

In [ ]:
print(df.iloc[0:2])

    crop  yield region
a  wheat     30   east
b   rice     60   west

In [ ]:
print(df.iloc[[0,2],[1,2]])

   yield region
a     30   east
c     45  north

In [ ]:
import pandas as pd
data={
    "farm":["farm1","farm2","farm3","farm4"],
    "crop": ["wheat","rice","maize","barley"],
    "area_ha":[10,12,14,15],
    "production_tons":[30,60,24,36]
}
df=pd.DataFrame(data)
print(df)

    farm    crop  area_ha  production_tons
0  farm1   wheat       10               30
1  farm2    rice       12               60
2  farm3   maize       14               24
3  farm4  barley       15               36

In [ ]:
df.head()

    farm    crop  area_ha  production_tons
0  farm1   wheat       10               30
1  farm2    rice       12               60
2  farm3   maize       14               24
3  farm4  barley       15               36

In [ ]:
df.head(2)

    farm   crop  area_ha  production_tons
0  farm1  wheat       10               30
1  farm2   rice       12               60

In [ ]:
df.tail()

    farm    crop  area_ha  production_tons
0  farm1   wheat       10               30
1  farm2    rice       12               60
2  farm3   maize       14               24
3  farm4  barley       15               36

In [ ]:
df.tail(2)

    farm    crop  area_ha  production_tons
2  farm3   maize       14               24
3  farm4  barley       15               36

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   farm             4 non-null      object
 1   crop             4 non-null      object
 2   area_ha          4 non-null      int64
 3   production_tons  4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [ ]:
df.describe()#summary statistics

         area_ha  production_tons
count   4.000000         4.000000
mean   12.750000        37.500000
std     2.217356        15.779734
min    10.000000        24.000000
25%    11.500000        28.500000
50%    13.000000        33.000000
75%    14.250000        42.000000
max    15.000000        60.000000

In [ ]:
#add a new column
#yld=production by area
df.yld_per_ha=df.production_tons/df.area_ha
print(df)

    farm    crop  area_ha  production_tons
0  farm1   wheat       10               30
1  farm2    rice       12               60
2  farm3   maize       14               24
3  farm4  barley       15               36

/tmp/ipython-input-2532020976.py:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.yld_per_ha=df.production_tons/df.area_ha

In [ ]:
df["yld_per_ha"]=df["production_tons"]/df["area_ha"]
print(df)

    farm    crop  area_ha  production_tons  yld_per_ha
0  farm1   wheat       10               30    3.000000
1  farm2    rice       12               60    5.000000
2  farm3   maize       14               24    1.714286
3  farm4  barley       15               36    2.400000

In [ ]:
print(df.iloc[[1,3]])

    farm    crop  area_ha  production_tons  yld_per_ha
1  farm2    rice       12               60         5.0
3  farm4  barley       15               36         2.4

In [ ]:
print(df.iloc[[1,3]],[0,1,2])

    farm    crop  area_ha  production_tons  yld_per_ha
1  farm2    rice       12               60         5.0
3  farm4  barley       15               36         2.4 [0, 1, 2]

In [ ]:
print(df.loc[[1,3],["farm","crop","area_ha"]])

    farm    crop  area_ha
1  farm2    rice       12
3  farm4  barley       15

In [ ]:
#filter data
#farms growing wheat
print(df["crop"]=="rice")
print()
wheat_farms=df[df["crop"]=="wheat"]
print(wheat_farms)

0    False
1     True
2    False
3    False
Name: crop, dtype: bool

    farm   crop  area_ha  production_tons  yld_per_ha
0  farm1  wheat       10               30         3.0

In [ ]:
#farms with yield greater than 3
high_yld=df[df["yld_per_ha"]>3]
print(high_yld)

    farm  crop  area_ha  production_tons  yld_per_ha
1  farm2  rice       12               60         5.0

In [ ]:
#sort farms by highest production
sorted_df=df.sort_values(by="production_tons",ascending=False)
print(sorted_df)

    farm    crop  area_ha  production_tons  yld_per_ha
1  farm2    rice       12               60    5.000000
3  farm4  barley       15               36    2.400000
0  farm1   wheat       10               30    3.000000
2  farm3   maize       14               24    1.714286

In [ ]:
#group operation avg yld per crop
avg_yld=df.groupby("crop")["yld_per_ha"].mean()
print(avg_yld)

crop
barley    2.400000
maize     1.714286
rice      5.000000
wheat     3.000000
Name: yld_per_ha, dtype: float64

In [ ]:
avg_yld=df.groupby("crop")["yld_per_ha"].sum()
print(avg_yld)

crop
barley    2.400000
maize     1.714286
rice      5.000000
wheat     3.000000
Name: yld_per_ha, dtype: float64